name: pose_tester
description: "A small app for testing pose logic on device"
publish_to: "none"
version: 1.145.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  auto_rula:
    git:
      url: https://github.com/fhstp/auto_rula.git
      ref: v1.1.0

  common: any
  common_ui: any
  fast_immutable_collections: ^11.0.0

  flutter:
    sdk: flutter

  fpdart: ^1.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  pose_detect: any
  pose_vis: any
  share_plus: ^10.1.4
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.1

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
