name: pose_transforming
version: 1.145.1
description: Pose transformation and normalization
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  auto_rula:
    git: git@github.com:fhstp/auto_rula.git

  common: any
  fast_immutable_collections: ^11.0.3
  meta: ^1.16.0
  pose_analysis: any
  vector_math: ^2.1.4

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^7.0.0
