name: pose_vis
version: 1.146.0
description: Pose visualization logic.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  auto_rula:
    git:
      url: https://github.com/fhstp/auto_rula.git
      ref: v1.1.1

  common: any

  flutter:
    sdk: flutter

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
