name: common_ui
description: Common ui logic for all ergo4all apps.
version: 1.145.2
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
