// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'session_storage/src/object_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5466712935554647132),
      name: 'IntPairEntity',
      lastPropertyId: const obx_int.IdUid(3, 3031064842075005473),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3857521377810484701),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1897231716671909857),
            name: 'first',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3031064842075005473),
            name: 'second',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7130293042528665444),
      name: 'RulaScoresEntity',
      lastPropertyId: const obx_int.IdUid(18, 3434131379598199514),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5005406819229077637),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8981991580760335933),
            name: 'upperArmPositionScoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 8710370597365555496),
            relationTarget: 'IntPairEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1082546081840463446),
            name: 'upperArmAbductedAdjustmentsId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 8698115318186200895),
            relationTarget: 'IntPairEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5292835707118627286),
            name: 'upperArmScoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 8831934900666586990),
            relationTarget: 'IntPairEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2662073106010035370),
            name: 'lowerArmPositionScoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 162882844582223296),
            relationTarget: 'IntPairEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8985309927265147905),
            name: 'lowerArmScoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 1908351803190765225),
            relationTarget: 'IntPairEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 259480228812824570),
            name: 'wristScoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 2630232548438602738),
            relationTarget: 'IntPairEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5996151232573167320),
            name: 'neckPositionScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1432525470205203585),
            name: 'neckTwistAdjustment',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4849097342540713261),
            name: 'neckSideBendAdjustment',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4263563177312386404),
            name: 'neckScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4003991478004306237),
            name: 'trunkPositionScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2761139933754394829),
            name: 'trunkTwistAdjustment',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4339200415566955372),
            name: 'trunkSideBendAdjustment',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 8244769609404499402),
            name: 'trunkScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 1488518581994251642),
            name: 'fullScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 3434131379598199514),
            name: 'legScoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 1584344419947150555),
            relationTarget: 'IntPairEntity')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 2854794524896638890),
      name: 'RulaSessionEntity',
      lastPropertyId: const obx_int.IdUid(3, 6954285411276052409),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2091664078688208030),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9161216521699097363),
            name: 'timestamp',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6954285411276052409),
            name: 'scenarioIndex',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'timeline',
            srcEntity: 'TimelineEntryEntity',
            srcField: 'session')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 5921173115527825764),
      name: 'TimelineEntryEntity',
      lastPropertyId: const obx_int.IdUid(4, 6186424656633553397),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8117780151674492886),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2074489264627736279),
            name: 'timestamp',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 845036351148957901),
            name: 'scoresId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 1143836385595101905),
            relationTarget: 'RulaScoresEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6186424656633553397),
            name: 'sessionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 1311924363503071673),
            relationTarget: 'RulaSessionEntity')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 5921173115527825764),
      lastIndexId: const obx_int.IdUid(9, 1584344419947150555),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [3404444209532274186],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    IntPairEntity: obx_int.EntityDefinition<IntPairEntity>(
        model: _entities[0],
        toOneRelations: (IntPairEntity object) => [],
        toManyRelations: (IntPairEntity object) => {},
        getId: (IntPairEntity object) => object.id,
        setId: (IntPairEntity object, int id) {
          object.id = id;
        },
        objectToFB: (IntPairEntity object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.first);
          fbb.addInt64(2, object.second);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final firstParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final secondParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = IntPairEntity(first: firstParam, second: secondParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    RulaScoresEntity: obx_int.EntityDefinition<RulaScoresEntity>(
        model: _entities[1],
        toOneRelations: (RulaScoresEntity object) => [
              object.upperArmPositionScores,
              object.upperArmAbductedAdjustments,
              object.upperArmScores,
              object.lowerArmPositionScores,
              object.lowerArmScores,
              object.wristScores,
              object.legScores
            ],
        toManyRelations: (RulaScoresEntity object) => {},
        getId: (RulaScoresEntity object) => object.id,
        setId: (RulaScoresEntity object, int id) {
          object.id = id;
        },
        objectToFB: (RulaScoresEntity object, fb.Builder fbb) {
          fbb.startTable(19);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.upperArmPositionScores.targetId);
          fbb.addInt64(2, object.upperArmAbductedAdjustments.targetId);
          fbb.addInt64(3, object.upperArmScores.targetId);
          fbb.addInt64(4, object.lowerArmPositionScores.targetId);
          fbb.addInt64(5, object.lowerArmScores.targetId);
          fbb.addInt64(6, object.wristScores.targetId);
          fbb.addInt64(7, object.neckPositionScore);
          fbb.addInt64(8, object.neckTwistAdjustment);
          fbb.addInt64(9, object.neckSideBendAdjustment);
          fbb.addInt64(10, object.neckScore);
          fbb.addInt64(11, object.trunkPositionScore);
          fbb.addInt64(12, object.trunkTwistAdjustment);
          fbb.addInt64(13, object.trunkSideBendAdjustment);
          fbb.addInt64(14, object.trunkScore);
          fbb.addInt64(16, object.fullScore);
          fbb.addInt64(17, object.legScores.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final neckPositionScoreParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final neckTwistAdjustmentParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final neckSideBendAdjustmentParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final neckScoreParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final trunkPositionScoreParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final trunkTwistAdjustmentParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final trunkSideBendAdjustmentParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          final trunkScoreParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          final fullScoreParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          final object = RulaScoresEntity(
              neckPositionScore: neckPositionScoreParam,
              neckTwistAdjustment: neckTwistAdjustmentParam,
              neckSideBendAdjustment: neckSideBendAdjustmentParam,
              neckScore: neckScoreParam,
              trunkPositionScore: trunkPositionScoreParam,
              trunkTwistAdjustment: trunkTwistAdjustmentParam,
              trunkSideBendAdjustment: trunkSideBendAdjustmentParam,
              trunkScore: trunkScoreParam,
              fullScore: fullScoreParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.upperArmPositionScores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.upperArmPositionScores.attach(store);
          object.upperArmAbductedAdjustments.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.upperArmAbductedAdjustments.attach(store);
          object.upperArmScores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.upperArmScores.attach(store);
          object.lowerArmPositionScores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.lowerArmPositionScores.attach(store);
          object.lowerArmScores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.lowerArmScores.attach(store);
          object.wristScores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.wristScores.attach(store);
          object.legScores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          object.legScores.attach(store);
          return object;
        }),
    RulaSessionEntity: obx_int.EntityDefinition<RulaSessionEntity>(
        model: _entities[2],
        toOneRelations: (RulaSessionEntity object) => [],
        toManyRelations: (RulaSessionEntity object) => {
              obx_int.RelInfo<TimelineEntryEntity>.toOneBacklink(4, object.id,
                      (TimelineEntryEntity srcObject) => srcObject.session):
                  object.timeline
            },
        getId: (RulaSessionEntity object) => object.id,
        setId: (RulaSessionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (RulaSessionEntity object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.timestamp);
          fbb.addInt64(2, object.scenarioIndex);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timestampParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final scenarioIndexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = RulaSessionEntity(
              timestamp: timestampParam, scenarioIndex: scenarioIndexParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<RulaSessionEntity>(
              object.timeline,
              store,
              obx_int.RelInfo<TimelineEntryEntity>.toOneBacklink(4, object.id,
                  (TimelineEntryEntity srcObject) => srcObject.session));
          return object;
        }),
    TimelineEntryEntity: obx_int.EntityDefinition<TimelineEntryEntity>(
        model: _entities[3],
        toOneRelations: (TimelineEntryEntity object) =>
            [object.scores, object.session],
        toManyRelations: (TimelineEntryEntity object) => {},
        getId: (TimelineEntryEntity object) => object.id,
        setId: (TimelineEntryEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TimelineEntryEntity object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.timestamp);
          fbb.addInt64(2, object.scores.targetId);
          fbb.addInt64(3, object.session.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timestampParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = TimelineEntryEntity(timestamp: timestampParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.scores.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.scores.attach(store);
          object.session.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.session.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [IntPairEntity] entity fields to define ObjectBox queries.
class IntPairEntity_ {
  /// See [IntPairEntity.id].
  static final id =
      obx.QueryIntegerProperty<IntPairEntity>(_entities[0].properties[0]);

  /// See [IntPairEntity.first].
  static final first =
      obx.QueryIntegerProperty<IntPairEntity>(_entities[0].properties[1]);

  /// See [IntPairEntity.second].
  static final second =
      obx.QueryIntegerProperty<IntPairEntity>(_entities[0].properties[2]);
}

/// [RulaScoresEntity] entity fields to define ObjectBox queries.
class RulaScoresEntity_ {
  /// See [RulaScoresEntity.id].
  static final id =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[0]);

  /// See [RulaScoresEntity.upperArmPositionScores].
  static final upperArmPositionScores =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[1]);

  /// See [RulaScoresEntity.upperArmAbductedAdjustments].
  static final upperArmAbductedAdjustments =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[2]);

  /// See [RulaScoresEntity.upperArmScores].
  static final upperArmScores =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[3]);

  /// See [RulaScoresEntity.lowerArmPositionScores].
  static final lowerArmPositionScores =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[4]);

  /// See [RulaScoresEntity.lowerArmScores].
  static final lowerArmScores =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[5]);

  /// See [RulaScoresEntity.wristScores].
  static final wristScores =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[6]);

  /// See [RulaScoresEntity.neckPositionScore].
  static final neckPositionScore =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[7]);

  /// See [RulaScoresEntity.neckTwistAdjustment].
  static final neckTwistAdjustment =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[8]);

  /// See [RulaScoresEntity.neckSideBendAdjustment].
  static final neckSideBendAdjustment =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[9]);

  /// See [RulaScoresEntity.neckScore].
  static final neckScore =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[10]);

  /// See [RulaScoresEntity.trunkPositionScore].
  static final trunkPositionScore =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[11]);

  /// See [RulaScoresEntity.trunkTwistAdjustment].
  static final trunkTwistAdjustment =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[12]);

  /// See [RulaScoresEntity.trunkSideBendAdjustment].
  static final trunkSideBendAdjustment =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[13]);

  /// See [RulaScoresEntity.trunkScore].
  static final trunkScore =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[14]);

  /// See [RulaScoresEntity.fullScore].
  static final fullScore =
      obx.QueryIntegerProperty<RulaScoresEntity>(_entities[1].properties[15]);

  /// See [RulaScoresEntity.legScores].
  static final legScores =
      obx.QueryRelationToOne<RulaScoresEntity, IntPairEntity>(
          _entities[1].properties[16]);
}

/// [RulaSessionEntity] entity fields to define ObjectBox queries.
class RulaSessionEntity_ {
  /// See [RulaSessionEntity.id].
  static final id =
      obx.QueryIntegerProperty<RulaSessionEntity>(_entities[2].properties[0]);

  /// See [RulaSessionEntity.timestamp].
  static final timestamp =
      obx.QueryIntegerProperty<RulaSessionEntity>(_entities[2].properties[1]);

  /// See [RulaSessionEntity.scenarioIndex].
  static final scenarioIndex =
      obx.QueryIntegerProperty<RulaSessionEntity>(_entities[2].properties[2]);

  /// see [RulaSessionEntity.timeline]
  static final timeline =
      obx.QueryBacklinkToMany<TimelineEntryEntity, RulaSessionEntity>(
          TimelineEntryEntity_.session);
}

/// [TimelineEntryEntity] entity fields to define ObjectBox queries.
class TimelineEntryEntity_ {
  /// See [TimelineEntryEntity.id].
  static final id =
      obx.QueryIntegerProperty<TimelineEntryEntity>(_entities[3].properties[0]);

  /// See [TimelineEntryEntity.timestamp].
  static final timestamp =
      obx.QueryIntegerProperty<TimelineEntryEntity>(_entities[3].properties[1]);

  /// See [TimelineEntryEntity.scores].
  static final scores =
      obx.QueryRelationToOne<TimelineEntryEntity, RulaScoresEntity>(
          _entities[3].properties[2]);

  /// See [TimelineEntryEntity.session].
  static final session =
      obx.QueryRelationToOne<TimelineEntryEntity, RulaSessionEntity>(
          _entities[3].properties[3]);
}
